ARG distro_image
ARG ROS_DISTRO

FROM $distro_image

# workspace setup

ENV WS /workspace
RUN echo "source ${WS}/install/setup.bash" >> ~/.bashrc
RUN echo "cd /workspace" >> ~/.bashrc

# Install ROS pkgs

RUN apt update -y

RUN DEBIAN_FRONTEND=noninteractive apt install -y python3-venv python3-pip
RUN DEBIAN_FRONTEND=noninteractive apt install -y vim nano

RUN DEBIAN_FRONTEND=noninteractive apt install -y python3-colcon-common-extensions

RUN DEBIAN_FRONTEND=noninteractive apt install -y ros-${ROS_DISTRO}-gazebo-ros
RUN DEBIAN_FRONTEND=noninteractive apt install -y ros-${ROS_DISTRO}-gazebo-msgs
RUN DEBIAN_FRONTEND=noninteractive apt install -y ros-${ROS_DISTRO}-gazebo-plugins
RUN DEBIAN_FRONTEND=noninteractive apt install -y ros-${ROS_DISTRO}-joint-state-publisher-gui
RUN DEBIAN_FRONTEND=noninteractive apt install -y ros-${ROS_DISTRO}-teleop-twist-keyboard

RUN DEBIAN_FRONTEND=noninteractive apt install -y ros-${ROS_DISTRO}-librealsense2*
RUN DEBIAN_FRONTEND=noninteractive apt install -y ros-${ROS_DISTRO}-realsense2-*

RUN DEBIAN_FRONTEND=noninteractive apt install -y ros-${ROS_DISTRO}-navigation2 ros-${ROS_DISTRO}-nav2-bringup
